### ISSUE TITLE
Kupo bug: Sometimes `datum_type` field is missing when `datum_hash` is not `null`

### ISSUE THREAD

**Issue by errfrom** [Plutonomicon/cardano-transaction-lib#1215]
According to the Kupo specification, an entry in the response to `GET /matches/{pattern}` must contain the `datum_type` field if `datum_hash` is present. This field specifies if the output should contain the full inline datum or just a hash, so that we can fetch the full datum via a separate request if `datum_type` is `inline` (see https://cardanosolutions.github.io/kupo/#operation/getAllMatches).

However, when manually testing this endpoint in the browser environment using Nami, this field is missing from the response, which leads to inline datums not being resolved. I wasn't able to reproduce this issue in Plutip environment though and haven't yet tested it against other browser wallets, so the problem may actually be with Nami.

**Comment by KtorZ** [comment]
That feature is brand-new and not yet released. So it would be good to check versions of Kupo is Nami currently using. Unless they use the latest master branch, the field will always be missing. 

Note also that I am not entirely sure what you refer to when you say testing this with Nami? I haven't played with Nami in a while so I may be missing context but does Nami has a way to plug Kupo in as a backend provider (via Lucid?) ? 

Besides, the title of the issue puzzles me. You say "sometimes", which suggests that there are cases where you see the datum_type field? Or do you mean that, you never see it when interacting with Nami, but see it otherwise on local instances? 
May you clarify that?

**Comment by errfrom** [comment]
@KtorZ Yes, the problem was that we weren't using the latest version of Kupo for our runtime. After using the Docker image with the `latest` tag, everything now works as expected. Thanks for pointing this out, it was very helpful!

By testing with Nami I meant trying to query utxos after submitting a transaction that produces the required outputs in the browser environment, so apologies for the confusion.

I put "sometimes" in the title because I was able to repeatedly reproduce this issue in the browser environment, but not when running our Plutip tests (which were executed using the latest version of Kupo).

**Comment by klntsky** [comment]
@KtorZ thank you very much!

@errfrom closing?
