### ISSUE TITLE
Handle NuFi `signData` response

### ISSUE THREAD

**Issue by errfrom** [Plutonomicon/cardano-transaction-lib#1266]
### Context
Currently we fail to parse NuFi `signData` response since it doesn't conform to the current version of [CIP-30](https://cips.cardano.org/cips/cip30/#apisigndataaddraddresspayloadbytespromisedatasignature). We expect the response to contain `signature` (`COSE_Sign1`) and `key` (`COSE_Key`) fields, but get hex-encoded CBOR bytes, which presumably correspond to the `COSE_Sign1` structure.

Compare these two responses (you can use https://cbor.nemo157.com/ to inspect CBOR):
Nami:  
```
key: "a40101032720062158208f5c2f5ad1a6b3b8a3ee45246f54c12901f45bfa9ffb2245d160a9cc009f255c"
signature: "845846a2012767616464726573735839005bb3534ddfca05e65461af994b952a9c50a59e9155e7ba57785392dda201bb51c680bf0065167a2c6d540396bda3f4ba3e35835ca197d0faa166686173686564f44c68656c6c6f20776f726c64215840cfdee7b9bed57d6de09bc3e78d8571c95d05e27e46d871487687b52123f011a2af6825db964a438c7745832e8072457aad37a9fdc75d672fb8424c971e054501"
```
NuFi:
```
"845869a3012704582071f207c27ba10d0b7fbd32084f3fcd0d8bc0b3cd8205b3df1d1438d730b8eff367616464726573735839005187dd62df74b927d4ae60791858ae67450c3f26df5dd19a2a1c9ad24ba6a63a33db7024fcfd929cde310548e9da9b39d464694e998d6441a166686173686564f44c68656c6c6f20776f726c64215840d1859df20e4f1f802e6a7029e4704d959dccf3576e50b51f92b68d77dc9a4e237ef4712a0ebb5ae308e1e7902180354c215f46d061e6275dc120869fe0b16104"
```
### Next steps:
1. Determine if NuFi `COSE_Sign1` structure contains the `kid` set to the verification key
2. Create `COSE_Key` structure using functionality from `Ctl.Internal.Wallet.Cip30.SignData` and patch the response
3. Use our testing approach from `Test.Ctl.Wallet.Cip30.SignData` to test `signData` of browser wallets

**Comment by klntsky** [comment]
We should ask the upstream to fix it instead of adapting for the upstream bug.

**Comment by klntsky** [comment]
Since there is no issue tracker on github, I posted in Discord:
https://discord.com/channels/884709419802308619/888429476558553138/1046750227895418910

**Comment by refi93** [comment]
Hi @klntsky , thanks for notifying us, We recently noticed this inconsistency and we plan to fix it in the upcoming days.

To give you some context, our implementation of the signData call is based on the "legacy" version of the call which can be found e.g. in Nami wallet: https://github.com/berry-pool/nami/blob/5db5ce074fa88288d986859fbf60b59dd7c90048/src/api/extension/index.js#L831 - we chose this implementation because we based our API on Flint wallet's API which implemented its `signData` call the same way together with several other wallets at the time (c.a. half a year ago)

Meanwhile, Flint already updated its `signData()` call in a breaking way and we'd do the same. I tried e.g. the https://cnft.io dapp which signs data on login and they seem to handle both the legacy and new format of output from the `signData` call, probably by checking whether the type of data returned is a `string` or not - that's how I'd recommend to handle this (sadly inevitably) breaking change on your side as well to work with older versions of the extension while users update their extension

**Comment by klntsky** [comment]
Thank you for the response @refi93 ! 

Could you please give an estimate for the new version release date?

**Comment by refi93** [comment]
we plan to submit the extension for review this week and, depending on how long the review takes, it will likely be live in the first half of the next week

**Comment by refi93** [comment]
@klntsky the new extension version fixing the signData() call has been released today :+1:

**Comment by errfrom** [comment]
@refi93 Thanks for fixing it so quickly!
I can confirm that the problem has been fixed on both mainnet and testnet wallets.

@klntsky @uhbif19 Closing the issue as resolved.
