### ISSUE TITLE
Improve jsonwsp parser tests.

### ISSUE THREAD

**Issue by adamczykm** [Plutonomicon/cardano-transaction-lib#132]
Our parser tests are only checking if the input was "validated" i.e. has expected structure and not if the parsing results are as expected. We may want to improve upon it.

_Originally posted by @adamczykm in https://github.com/Plutonomicon/cardano-browser-tx/issues/130#issuecomment-1044695957_

**Comment by Benjmhart** [comment]
some info on the original parser testing plan @ngua this may make it into the test plan

- we used Medea for these so that we could document the structure in the form of a medea Schema
- we collect a series of example json which should both pass the Medea Schema and our parser.
- as parsing bugs are found, you add the json of the bug-inducing data to your fixtures, correct the medea schema if necessary, and then adjust the parser as needed.

this really helps prevent regressions in my experience.

**Comment by klntsky** [comment]
We don't really care about particular values, only about the format.
