### ISSUE TITLE
Add more wallets

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#141]
We currently only support Nami but will need to add more wallets in the future. Some possibilities:

- Yoroi
- Typhon
- Gero
- CCVault

**Comment by Benjmhart** [comment]
Typhon might work well for a non-browser wallet,   otherwise we may need to run the `cardano-wallet` AKA Wallet backend for testing activity.

For non-Browser wallets, we likely want a setting where instead of submitting a transaction, we write it to disk to be picked up by a haskell process in some cases (making assertions about the transaction itself, running it against a virtual environment, etc.

**Comment by Benjmhart** [comment]
Eternl wallet is really popular right now as well.

**Comment by klntsky** [comment]
- Lace #555
- Flint #556

**Comment by klntsky** [comment]
Eternl - #744

**Comment by uhbif19** [comment]
I did not find a testing option for Typhoon. It seems like there is no test extension and regular extension does not allow to change networks.

**Comment by klntsky** [comment]
Let's open new issues on per wallet basis
