### ISSUE TITLE
Correct implementation for `PublicKey` with newtypes over `Bech32String`

### ISSUE THREAD

**Issue by vvtran** [Plutonomicon/cardano-transaction-lib#242]
At the moment, `PublicKey` is a newtype wrapper over `Bech32String` which is an alias of `String`, the issue is the string can be different lengths so some further newtype wrappers over `String` would probably make sense.

 For example, we can use `ed25519KeyHashFromBech32 :: Bech32String -> Maybe Ed25519KeyHash` on an input like `"addr_vkh1zuctrdcq6ctd29242w8g84nlz0q38t2lnv3zzfcrfqktx0c9tzp"` but not
`"addr1qyc0kwu98x23ufhsxjgs5k3h7gktn8v5682qna5amwh2juguztcrc8hjay66es67ctn0jmr9plfmlw37je2s2px4xdssgvxerq"`. However,
we can use `addressBech32 :: Address -> Bech32String` on the latter.

I believe this is because the former being an enterprise address (no staking credentials), and hence shorter. Feel free to correct my understanding on this.

This means `QueryM.ownPubKeyHash`  and `UnbalancedTransaction.pubKeyHash :: PublicKey -> Maybe PubKeyHash`  are currently incorrect, a correct implementation can be found on this commit https://github.com/Plutonomicon/cardano-browser-tx/pull/241/commits/5dd54e1a0e89e2c289bee7b51a63d0128f7777e3 which goes via `StakeCredential`-related functions. But if we implement `PublicKey` properly, the fix should be unnecessary.

Note: the lack of `PublicKey` is not a blocker for Seabug but means our `ScriptLookups` are restricted as seen in the mentioned commit. However, the related issue of `Address` is currently a critical bug - see https://github.com/Plutonomicon/cardano-browser-tx/issues/243

**Comment by adamczykm** [comment]
`ed25519KeyHashFromBech32` is a function that parses Bech32 representation of PKH into its CSL representation. It will fail if some bech32 encoded string does not represent PKH, which is expected behavior.
Bech32 is just a string representation of bytes that is less human error-prone and has a human-readable header. The only downfall of having it aliased and not newtyped is related to Bech32String being a subset of proper strings, so some string inputs might be unexpected by functions expecting Bech32String, but it doesn't seem to be the case for CSL.
