### ISSUE TITLE
Fix `pubKeyHash...Address`

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#295]
The staking credential component of `pubKeyHashBaseAddress` appears to be incorrect. For example, `getWalletAddress` and `payPubKeyHashBaseAddress networkId <$> ownPaymentPubKeyHash` don't match

**Comment by klntsky** [comment]
The difference is because `paymentCred` and `delegationCred` are constructed from the same `StakeCredential`  in `pubKeyAddress`. This stake credential is in turn received from `addressPaymentCred` which calls `payment_cred()` on given a `BaseAddress` constructed from `Address`.

So I guess `pubKeyAddress` should just be fixed, everything depending on it should pass two arguments for two types of credentials.
