### ISSUE TITLE
Allow querying without collateral

### ISSUE THREAD

**Issue by nrutledge** [Plutonomicon/cardano-transaction-lib#374]
Users currently require a wallet with collateral set in order to perform query actions (e.g., fetching NFTs to view in a marketplace). This is problematic for a couple reasons:
1. Users may not have wallets installed (or have wallets without collateral) but want to view blockchain data.
2. Users with wallets are prompted to connect their wallet just to query data.

We should completely remove the wallet requirement for queries that do not involve wallet utxos if possible.

**Comment by ngua** [comment]
Querying without a wallet is possible now (I fixed it when the issue originally happened with Seabug)

For collateral, this might be an issue. We need to filter out the collateral utxo from those returned by `utxosAt`. AFAIK if collateral is not set, Nami will still return some of the user's UTxOs. Since we have no way of knowing what is genuine collateral, we still attempt to filter out what Nami returns, leading to what can appear to be strange bugs

**Comment by klntsky** [comment]
@ngua what if we modify our wallet initialization code to allow the app developers to specify if they need a collateral? 

I'm introducing a `WalletSpec` type here - https://github.com/Plutonomicon/cardano-transaction-lib/pull/731

We could just extend it with a boolean flag to require collateral presence.

**Comment by klntsky** [comment]
Done.
