### ISSUE TITLE
AlwaysSucceeds example instantiates nami wallet twice

### ISSUE THREAD

**Issue by jy14898** [Plutonomicon/cardano-transaction-lib#472]
We should just be able to replace

https://github.com/Plutonomicon/cardano-transaction-lib/blob/c5883ebaf400556f9e5ac973d5a0b1c30011e082/examples/AlwaysSucceeds.purs#L34-L35

with

```haskell
 cfg <-traceContractConfig 
```

as `traceContractConfig` by default uses the Nami wallet

**Comment by klntsky** [comment]
I think `traceContractConfig` should be removed. We can't provide meaningful defaults when choosing between apples and oranges, let's ask users to explicitly initialize wallets and services, even if it's done just by providing default configs.

The reason is: it's easier to change a config when it's explicitly passed. Otherwise one needs to copy-paste a huge amount of code to change one parameter.

**Comment by klntsky** [comment]
Closed by #543
