### ISSUE TITLE
`Alt`, `Plus` and `Alternative` instances for Contract

### ISSUE THREAD

**Issue by adamczykm** [Plutonomicon/cardano-transaction-lib#605]
It'd be useful to have an `Alternative` instance for `Contract`.

**Comment by adamczykm** [comment]
Why `Effect`? `Aff` has it

**Comment by adamczykm** [comment]
Potential use case?
```
txId <- liftedM (getOwnUtxo filtr)  <|> createSomeUtxo
```

**Comment by klntsky** [comment]
Didn't know about aff having it, let's discuss more.

Our current problem is that LoggerT does not have an instance. What can we do with logs? Probably they will have to be combined between alternatives, since LoggerT is just a readerT with  a message handling callback function. I think it is acceptable if `Aff` has it, since logging is indistinguishable from arbitrary IO effects in terms of type class laws.

I created an [issue](https://github.com/cprussin/purescript-monad-logger/issues/7) upstream, but obviously it is not blocking us from adding our instance.

**Comment by adamczykm** [comment]
No LoggerT nor ReaderT may modify the "evaluation context" of subsequent Contract actions, thus we should be fine piggie-backing on Aff instances for Alt and Plus and ignoring the aforementioned transformers.
