### ISSUE TITLE
Rework `purescriptProject` components to avoid recompilation

### ISSUE THREAD

**Issue by marijanp** [Plutonomicon/cardano-transaction-lib#655]
Overriding `buildPursProject` inside `runPursTest` is a bad Idea because it causes compilation for the purescript project to happen at least twice. Once for the project derivation itself and then everytime `runPursTest` is called. To avoid this, instead of overriding using `overrideAttrs`, doing this in the `checkPhase`
```
 node -e 'require("./output/${testMain}").main()' 
```
we should use the trivial-builder `runCommand` and reuse the result of `buildPursProject`, meaning
```
 text = "${pkgs.node}/bin/node -e 'require("${ project-derivation }/${ testMain }").main()' 
```
where
```
project-derivation = project.buildPursProject {...};
```

**Comment by ngua** [comment]
This is part of a larger change that needs to happen. The original idea was to allow users to specify project components since we can't generate those from the dhall configs. Unfortunately purs doesn't support partial/incremental compilation, so we can't build part of the project and use it elsewhere. This means that we always need to build all PS modules from the whole `src`
