### ISSUE TITLE
Factor out common code in ogmios/ogmiosdatumcache websocket constructors

### ISSUE THREAD

**Issue by jy14898** [Plutonomicon/cardano-transaction-lib#664]
`mkOgmiosWebSocket'` and `mkDatumCacheWebSocket'` are implemented almost identically, modulo naming and specific listeners. We could create a `mkWebSocket'` function which uses type-class machinery to iterate over the row containing the listeners:

```haskell
type WebSocketName = String

mkWebSocket'
  :: forall (row :: Row Type)
   . MachineryOverRow row
  => WebSocketName 
  -> LogLevel
  -> ServerConfig
  -> (Either Error (WebSocket row) -> Effect Unit)
  -> Effect Canceler
```

This is useful elsewhere, like in #642, where I wanted to create a WebSocket that could generate raw Ogmios Aeson responses to be used as fixtures

**Comment by klntsky** [comment]
I suggest applying a handle pattern here, instead of type-level dispatching.

We can move
- `createMutableDispatch` / `createPendingRequests` calls
- `resendPendingRequests`
- instantiation of `OgmiosWebSocket` record
- service name as `String` (`Ogmios` vs. `Ogmios Datum Cache`) 
into a handle.

I'm against type classes that have no obvious or explicitly defined laws
