### ISSUE TITLE
lib.BigNum.one is not a function

### ISSUE THREAD

**Issue by hyphenrf** [Plutonomicon/cardano-transaction-lib#815]
An error I kept facing while doing `spago repl`, I'm not sure if it's intentional or not, but this https://github.com/Plutonomicon/cardano-transaction-lib/blob/2a12009ec2f7fa870c070d7aa05a5f41d723c6f3/src/Types/BigNum.js#L14 calls a nonexistent function:
```js
> const lib = require('@emurgo/cardano-serialization-lib-nodejs');
undefined
> lib.BigNum.one;
undefined
> lib.BigNum.zero;
[Function: zero]
```

**Comment by hyphenrf** [comment]
should it be `lib.BigNum.from_str('1');`? That seems to work

**Comment by ngua** [comment]
@hyphenrf Are you using `npm` directly? Do you have a `node_modules` present? This is something users have reported when using `npm install` instead of having Nix manage the node dependencies (done automatically with `nix develop`, but if you have `node_modules` present in the working directory it will shadow the ones from the Nix store)

**Comment by ngua** [comment]
> should it be lib.BigNum.from_str('1');? That seems to work
No, `one` is a defined symbol in `cardano-serialization-lib`

**Comment by ngua** [comment]
On latest `develop`:

```
Welcome to Node.js v14.19.1.
Type ".help" for more information.
> const lib = require("@emurgo/cardano-serialization-lib-nodejs")
undefined
> lib.BigNum.one
[Function: one]
>
```

**Comment by hyphenrf** [comment]
thanks, confirmed this works :heart:
I'll pay more attention to my `npm` calls, forgot the `--package-lock-only`
