### ISSUE TITLE
Enforce locale when calling `initdb`

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#828]
From slack:

> If anyone is testing out the new plutip integration and runs into issues with initdb saying to check LANG and LC_* : I started with [this error](https://stackoverflow.com/questions/41956994/initdb-bin-invalid-locale-settings-check-lang-and-lc-environment-variables) and followed steps from that link, then was getting [this error](https://askubuntu.com/questions/114759/warning-setlocale-lc-all-cannot-change-locale) and followed steps from there, then closed my shell and opened it and things were working

We should set these for initdb:

```
LC_ALL="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
```

**Comment by MitchyCola** [comment]
I had to follow these instructions to fix the errors on my machine: https://nixos.wiki/wiki/Locales

**Comment by klntsky** [comment]
We just observed it again.

**Comment by kirill-havryliuk** [comment]
Indeed, running `npm run plutip-test`, or `spago run --main Test.Ctl.Plutip`, which are ste same, under `nix develop` shell, will get you and initdb error. Either something like `initdb saying to check LANG and LC_*` as in description, or ` Error: Process initdb ...  did not exit cleanly`. I have observed both. 

Turns out we are not alone with such a problem. The similar issues are:
 - https://github.com/NixOS/nixpkgs/issues/60414
 - https://gist.github.com/gusmacaulay/9dc5793439750912458f3c6a8945de7d
 
While it is, probably, possible to set LC_* variables to some particular locale, like C, I observed, that setlocale inside shell can't pick up locales from host system. In my case, I wasn't able to set locale to en_US.UTF-8 in shell, despite it is definitely exists on host.

The solution of this problem, described in aforementioned issues: inclusion of glibcLocales package into shell environment.
