### ISSUE TITLE
Add alternative, "simple" balancing strategy

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#892]
In its current state, the balancer will _always_ call provided scripts with an unbalanced transaction (we are using a recursive approach to calculating fees and ex units, and scripts are evaluated as part of the second step). This should lead to more accurate fees, but will also cause problems for projects whose validators assume certain properties about the `ScriptContext`'s inputs and outputs (and reasonably so -- such assumptions are part of many valid scenarios for script validation)

We should support a simpler approach to balancing where the execution units are only called at the very end, when the transaction has already been balanced. We need to find a way to ensure that fees are sufficient as these might be affected by the ex units 

We can perhaps refer to `Berry-Pool`'s fork of CML which includes a balancer in this style: https://github.com/Berry-Pool/cardano-multiplatform-lib/blob/plutus/rust/src/tx_builder.rs#L1783 (the ex unit endpoint is only called at the very end)

To be clear, we should **not** remove the current balancer. Instead we should add a `data BalancingStrategy = Simple | Recursive` or similar datatype and take this as a parameter to an extended `balanceTxWithStrategy`, where the current `balanceTx` would be `balanceTxWithStrategy Recursive`. This might lead to several different `balanceTx...` variants when combined with the `...WithAddress` ones, but given that users cannot work around this themselves, I think that is an acceptable consequence

**Comment by jy14898** [comment]
There's also the option of running `Recursive` initially, and if evaluation fails, fall back to `Simple`?

**Comment by maciej-bendkowski** [comment]
> There's also the option of running `Recursive` initially, and if evaluation fails, fall back to `Simple`?

That sounds to me like a third scenario. To me, the two strategies take two sides of the balancing trade-off :
1. Simple - _always_ balances if the transaction can be balanced, but perhaps uses inaccurate fees, and
2. Recursive - attempts to optimise the fees, but might fail under certain circumstances.

**Comment by maciej-bendkowski** [comment]
Clearly, the circumstances under which the `Recursive` strategy might fail should be made _explicit_. Perhaps one of them might return a `BalancedTx` whereas the other returns something like `Maybe BalancedTx`?

**Comment by klntsky** [comment]
Can we try to _reduce_ fees in a loop after over-estimating them?

**Comment by ngua** [comment]
If we always switch to `Simple` when script evaluation fails, we will be doing so for _all_ possible script evaluation failures. In the vast majority of cases, this will be spurious. We _cannot_ know when a validator fails because it assumes the inputs and outputs in the `ScriptContext` are balanced. This will add a large amount of overhead and isn't worth it IMO

**Comment by klntsky** [comment]
> This will add a large amount of overhead and isn't worth it IMO

I am not convinced. Original algorithm can fail or pass, and simple algorithm can fail or pass, there are 4 cases. We don't make things worse for `11` and `10` cases, but we significantly improve the `01` case (it's failure vs. success) and slightly degrade performance for `00` case (~2x longer waiting time). IMO it is worth it. Regarding user choice, we can let the user specify strategy. But we should make it possible to use CTL without even knowing what balancing is.

**Comment by maciej-bendkowski** [comment]
> Can we try to reduce fees in a loop after over-estimating them?
It might be tricky if you add an additional input with the fees. In principle adding a single UTxO pair (input / output) might change the ex budget arbitrarily. That being said, a more careful treatment should succeed.

> Regarding user choice, we can let the user specify strategy. But we should make it possible to use CTL without even knowing what balancing is.

Isn't the current slowdown caused by async communication with the server anyway? As a user, I could wait a while if it meant that I don't have to care about balancing strategies.

**Comment by errfrom** [comment]
What if we, instead of implementing several parallel strategies, would provide an additional constraint (something like `mustGenerateChangeOutputForAddress`), which should be enough to ensure we have a partially balanced transaction for a specified address. Thus, it will cover the specific requirement you have in your contract and expand the set of possible contracts supported by the current balancing strategy, given that the balancing problem is undecidable. Over time, we will probably explore some new requirements users would like to enforce, so we will be able to extend our constraint system accordingly without having to implement a new balancing strategy each time, which is non-trivial and buggy.
